# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value
#  nationalRail.class: NationalRailBundle\Utils\NationalRail

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  #app.nationalRail:
  #        class: "%nationalRail.class%"


